import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface Transaction {
  _id?: string;
  id?: string;
  name?: string;
  description?: string;
  note?: string;
  amount: number;
  date: string | Date;
}

export const generateTransactionsPDF = (
  personName: string,
  transactions: Transaction[]
): void => {
  const doc = new jsPDF();

  // Add centered person name with elegant styling
  const pageWidth = doc.internal.pageSize.getWidth();
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  const nameWidth = doc.getTextWidth(personName);
  const nameX = (pageWidth - nameWidth) / 2;
  doc.text(personName, nameX, 20);

  // Add date
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const dateText = `Generated on: ${new Date().toLocaleDateString()}`;
  const dateWidth = doc.getTextWidth(dateText);
  const dateX = (pageWidth - dateWidth) / 2;
  doc.text(dateText, dateX, 30);

  // Calculate total
  const total = transactions.reduce((sum, t) => sum + t.amount, 0);

  // Prepare table data
  const tableData = transactions.map((transaction, index) => [
    (index + 1).toString(),
    transaction.note || transaction.name || transaction.description || "N/A",
    transaction.amount.toFixed(2),
  ]);

  // Add table
  autoTable(doc, {
    startY: 40,
    head: [["#", "Transaction Name", "Amount"]],
    body: tableData,
    theme: "grid",
    headStyles: {
      fillColor: [66, 139, 202],
      fontSize: 11,
      fontStyle: "bold",
    },
    styles: {
      fontSize: 10,
      cellPadding: 5,
    },
    margin: { top: 40 },
    columnStyles: {
      0: { cellWidth: 15 },
      1: { cellWidth: 120 },
      2: { cellWidth: 40 },
    },
  });

  // Add total
  const finalY =
    (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable
      .finalY || 40;
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(`Total Amount: ${total.toFixed(2)}`, 14, finalY + 15);

  // Add footer
  doc.setFontSize(8);
  doc.setFont("helvetica", "italic");
  doc.text("Generated by FinTrack", 14, doc.internal.pageSize.height - 10);

  // Save PDF
  const fileName = `${personName.replace(
    /\s+/g,
    "_"
  )}_transactions_${Date.now()}.pdf`;
  doc.save(fileName);
};
